spring:
  datasource:
    driver-class-name:
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    open-in-view: false
    show-sql: true
  thymeleaf:
    prefix: classpath:/static/
    suffix: .html
  web:
    resources:
      static-locations: classpath:/static/
  data:
    redis:
      repositories:
        enabled: false

file:
  size:
    image: 3145728 # 3 * 1024 * 1024
    video: 104857600 # 100 * 1024 * 1024
    replay: 52428800 # 50 * 1024 * 1024

aws:
  s3:
    region: ENC(EIB2g/U4jVzHosi9QUosPlU+tFP6H/lcluc/kMGFXPPTM+XFr9ap+XZ2X80R/cDD)
    access-key: ENC(Q8A57jwYD1bYbHjlCk4vEPYL46/dDiys1YwLa1y6mjMCNOhcKFOcFkJ6w8YsT+zx4GacUhpJXcRuFBgObw4SyA==)
    secret-key: ENC(ICpaLWfg2Snb4PNQ31gIUMAdT8zlSgOKnT5gJ0jXnCUPPIpJfXex2wOBQw/cN/C/BpPBrx8JLMgNoWkULQIaENyfnyzAXSZrgIOyqPBip4E=)
    buket: ENC(sfiYuacgnGosgyqbK+t1It57iGZ0KPdPyGP32qjHxIhQ2uegFzP4Qbelz7SF9ZCg)
    host: ENC(BVVl7wcbGFzwYtfrpqD0ZY2C1RLFJD1V1toKZqd9mYcahNy4PL0n4hrXkwVP9j4D04l2bEOyqQBeSRxGBZAlRCS7gk5BPf2DaodI5sFlWAq3FtA/FhvcayQ20l+bAott)


# LOCAL
---
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
  mail:
    google:
      host: smtp.gmail.com
      username: ENC(Lk0dKUD0pcJlm2qHavIn4VKi2OPONEBTokAaGZ/4+NJsvsze2+ZgkS80yD5v8/VbAm69nGlli/c5xSXAAXjVzQ==)
      password: ENC(EFNYRs7rjs5O8bPWEUQ5eVbWFPbZ3kYOV6GI1Jw7LUo6CRXuU2AY1U67Mw7dmxTFK+WiAW3/AWUVzprTNRoGSg==)
      port: 587
  redis:
    host: chzh85991.cafe24.com
    port: 23699
    password: redis12!@
  config:
    activate:
      on-profile: local

google:
  auth:
    url: https://oauth2.googleapis.com
    scope: profile,email,openid
  login:
    url: https://accounts.google.com
  redirect:
    uri: http://cground.store/lawgg-spring/api/public/google/login/redirect
  client:
    id: ENC(IGl59N1wTjN+wWRcY3iJsC4Vj5cRsVmicaIugYCFJG2M1pa0q+0dDht/hQ7as1tUrmjVNifKuUxiGwdHPmijmj+fBE+FNAY/hPhj2tDWpJ8=)
  secret: ENC(u1WyUSfdY3sqB3TfWGj1R2E8Vis3OLELOMdV1fgjH6pDtbdqZ1SQhJEfG1WqE1rvOdzHTFOTez7HKcyDIbd/QEJsXq0/sAdm004x40jrCBw=)

naver:
  auth:
    url: https://openapi.naver.com
  login:
    url: https://nid.naver.com
  redirect:
    uri: http://cground.store/lawgg-spring/api/public/naver/login/redirect
  client:
    id: ENC(C7pqR2liF675VuEbQdv/S+O4wCHY5Lgx+XuF+gAeBCCVB18ykCPdjFIfjANw/KA4nBBsAxi/uF3vWH/PimefPQ==)
  secret: ENC(71ey5lTH3IAerQwhXbyfdP6R8vb2sz+A2ypn5SysxJa+SO3ZqXt7p+LrvOqMAXnH)

kakao:
  auth:
    url: https://kapi.kakao.com
  login:
    url: https://kauth.kakao.com
  redirect:
    login:
      uri: http://cground.store/lawgg-spring/api/public/kakao/login/redirect
    logout:
      uri: http://cground.store/lawgg-spring/api/public/kakao/logout/redirect
  client:
    id: ENC(nL/Dkn2NOC4bi/y2imKzGiCh7yYQD+xaktmWOcJJYUepL/xPd4JVPtluDnzLg9/zitTdNppHVFd7HFK5E3CsdpZtVOsbcUZ4/PtsFppi3h0=)
  secret: ENC(j+Jvpv9kqzIOt46Lo0VppBgUPbwkoFgO5s3fO68zA6tj3ONk8Y3uMWFPGbHJU34j0zrT8qa0UeU+bwr+jSy1RdAUOYimBRUj87urqdRCpqM=)

# TEST
---
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
  mail:
    google:
      host: smtp.gmail.com
      username: ENC(Lk0dKUD0pcJlm2qHavIn4VKi2OPONEBTokAaGZ/4+NJsvsze2+ZgkS80yD5v8/VbAm69nGlli/c5xSXAAXjVzQ==)
      password: ENC(EFNYRs7rjs5O8bPWEUQ5eVbWFPbZ3kYOV6GI1Jw7LUo6CRXuU2AY1U67Mw7dmxTFK+WiAW3/AWUVzprTNRoGSg==)
      port: 587
  redis:
    host: chzh85991.cafe24.com
    port: 23699
    password: redis12!@
  config:
    activate:
      on-profile: test

google:
  auth:
    url: https://oauth2.googleapis.com
    scope: profile,email,openid
  login:
    url: https://accounts.google.com
  redirect:
    uri: http://cground.store/lawgg-spring/api/public/google/login/redirect
  client:
    id: ENC(QabZPzwFQTu5S7Agv+jJyldTB4u5HDrP+tV25ajHWkKt8uaEL7N4zj4YqPefb0r+oAnk9vCFyRjBf0JZ6LHnFUGrrfd1N3zoAfeFxDSu6pA=)
  secret: ENC(KEPMb6NhLiZr+JjJ2qqJkzv8DlRrdOVv7cpYf8lE/wegVlfgYFvwDBy+y8s2dQGq0G72ruPI0hYmK8DsRytGyy3U4siR16sQZVVbq/HYJgM=)

naver:
  auth:
    url: https://openapi.naver.com
  login:
    url: https://nid.naver.com
  redirect:
    uri: http://cground.store/lawgg-spring/api/public/naver/login/redirect
  client:
    id: ENC(dDIGXFoIlq0tDwtnzy2NRxszNGZ+bX9Oat+L1qLsiJfQCs24rEkZltUQdcO9DQGvLpL6rJVy3Ux4/Bks89syxw==)
  secret: ENC(+6vs2ewUgYyvFcAlvG8y2eskG6Xq3VfyaV+SzBsvy+TkrwL/125v84LI8LpZQ7yY)


kakao:
  auth:
    url: https://kapi.kakao.com
  login:
    url: https://kauth.kakao.com
  redirect:
    login:
      uri: http://cground.store/lawgg-spring/api/public/kakao/login/redirect
    logout:
      uri: http://cground.store/lawgg-spring/api/public/kakao/logout/redirect
  client:
    id: ENC(B25W24lylSyzENGt7DZuZ4bf02ZoJjPONHwGyjd4BA2rF1A4a3/ZFnJQ5fIFj746LmYwsrk3q0+sMdi+a+jRm48uGFIk6o74beu+ebK/leg=)
  secret: ENC(XGwdt4ki0xT+JEDN0W6goFMY/PqnNcU/hw6XzGIYYywLVL/FAHvkDpAeoo9zS6hPO9RSUrSp2jY0anUYbriKGBtCJgasu7HYgtlNrd+86Zc=)

# PROD
---
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
  mail:
    google:
      host: smtp.gmail.com
      username: ENC(Xr4rkO+eirBw3WtwLkCqCumPO4EXrq5uXSb5S8P36IDIkAgYCZD3nNSZ/gPmsgqb6I5pTirWxbwArUm2P3swjw==)
      password: ENC(oUJZvRndHDE4JslXIJkaMMml/85S/f5aNjvh1KmgdT8MtKHCpcxOS0NH1zfT1UsunTn1Ul6tn3jPXIJAYmuluQ==)
      port: 587
  redis:
    host: chzh85991.cafe24.com
    port: 23699
    password: redis12!@
  config:
    activate:
      on-profile: prod

google:
  auth:
    url: https://oauth2.googleapis.com
    scope: profile,email,openid
  login:
    url: https://accounts.google.com
  redirect:
    uri: http://cground.store/lawgg-spring/api/public/google/login/redirect
  client:
    id: ENC(QabZPzwFQTu5S7Agv+jJyldTB4u5HDrP+tV25ajHWkKt8uaEL7N4zj4YqPefb0r+oAnk9vCFyRjBf0JZ6LHnFUGrrfd1N3zoAfeFxDSu6pA=)
  secret: ENC(KEPMb6NhLiZr+JjJ2qqJkzv8DlRrdOVv7cpYf8lE/wegVlfgYFvwDBy+y8s2dQGq0G72ruPI0hYmK8DsRytGyy3U4siR16sQZVVbq/HYJgM=)

naver:
  auth:
    url: https://openapi.naver.com
  login:
    url: https://nid.naver.com
  redirect:
    uri: http://cground.store/lawgg-spring/api/public/naver/login/redirect
  client:
    id: ENC(dDIGXFoIlq0tDwtnzy2NRxszNGZ+bX9Oat+L1qLsiJfQCs24rEkZltUQdcO9DQGvLpL6rJVy3Ux4/Bks89syxw==)
  secret: ENC(+6vs2ewUgYyvFcAlvG8y2eskG6Xq3VfyaV+SzBsvy+TkrwL/125v84LI8LpZQ7yY)

kakao:
  auth:
    url: https://kapi.kakao.com
  login:
    url: https://kauth.kakao.com
  redirect:
    login:
      uri: http://cground.store/lawgg-spring/api/public/kakao/login/redirect
    logout:
      uri: http://cground.store/lawgg-spring/api/public/kakao/logout/redirect
  client:
    id: ENC(B25W24lylSyzENGt7DZuZ4bf02ZoJjPONHwGyjd4BA2rF1A4a3/ZFnJQ5fIFj746LmYwsrk3q0+sMdi+a+jRm48uGFIk6o74beu+ebK/leg=)
  secret: ENC(XGwdt4ki0xT+JEDN0W6goFMY/PqnNcU/hw6XzGIYYywLVL/FAHvkDpAeoo9zS6hPO9RSUrSp2jY0anUYbriKGBtCJgasu7HYgtlNrd+86Zc=)