server:
  port: 19001
  shutdown: graceful
  servlet:
    context-path: /lawgg

spring:
  application:
    name: lawgg-spring
  profiles:
    active: local
    include:
      - core
      - gateway
      - dao
    group:
      local:
        - console-logging # 콘솔 로깅만 사용
      test:
        - console-logging
        - file-logging # 파일 로깅 사용
      prod:
        - console-logging
        - file-logging # 파일 로깅 사용
  config:
    import: optional:configserver:http://spring-cloud-config:8888/ # spring cloud config 정보 조회 (서버 종료 option 처리)
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    open-in-view: false
    show-sql: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  data:
    redis:
      repositories:
        enabled: false

mybatis:
  type-aliases-package: com.kr.lg.mapper
  mapper-locations: classpath:mapper/*.xml
