lg:
  redirect:
    url:
      home: http://localhost:8080/
      login: http://localhost:8080/login
  logout:
    url: http://localhost:8080/

portone:
  rest:
    key: ENC(ZZ02Cc5d0J859mcQUIViypAVpREP72m+hAPDia/3Gynu9+y3zOAfjFat+fxRZZjrLIe32Da4ceViVWeJUbVLzA==)
    secret: ENC(GTUQ/3h3/tK4Qa/KskCOtZiJNdpX0/7Yon4gccyavWeCqe/uSfmSD8AfUpwtXLzqvny4i/HcPi0nXEJlYQecwn5OKo7x9ttKBIiHQ96GIBChCsmEMzb6jTP5z5dAZ/87umy/Z7JYaXb/kECzeq4xazPbT3k9Mdj+Tb6RHGptN24=)
  url:
    token: https://api.iamport.kr/
    certificate: https://api.iamport.kr/certifications/

token:
  access-expired-time: 3600
  refresh-expired-time: 604800

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
  mail:
    google:
      host: smtp.gmail.com
      username: ENC(Lk0dKUD0pcJlm2qHavIn4VKi2OPONEBTokAaGZ/4+NJsvsze2+ZgkS80yD5v8/VbAm69nGlli/c5xSXAAXjVzQ==)
      password: ENC(EFNYRs7rjs5O8bPWEUQ5eVbWFPbZ3kYOV6GI1Jw7LUo6CRXuU2AY1U67Mw7dmxTFK+WiAW3/AWUVzprTNRoGSg==)
      port: 587
  redis:
    host: chzh85991.cafe24.com
    port: 23699
    password: redis12!@
  config:
    activate:
      on-profile: local

google:
  auth:
    url: https://oauth2.googleapis.com
    scope: profile,email,openid
  login:
    url: https://accounts.google.com
  redirect:
    uri: http://cground.store/lawgg-spring/api/public/google/login/redirect
  client:
    id: ENC(IGl59N1wTjN+wWRcY3iJsC4Vj5cRsVmicaIugYCFJG2M1pa0q+0dDht/hQ7as1tUrmjVNifKuUxiGwdHPmijmj+fBE+FNAY/hPhj2tDWpJ8=)
  secret: ENC(u1WyUSfdY3sqB3TfWGj1R2E8Vis3OLELOMdV1fgjH6pDtbdqZ1SQhJEfG1WqE1rvOdzHTFOTez7HKcyDIbd/QEJsXq0/sAdm004x40jrCBw=)

naver:
  auth:
    url: https://openapi.naver.com
  login:
    url: https://nid.naver.com
  redirect:
    uri: http://cground.store/lawgg-spring/api/public/naver/login/redirect
  client:
    id: ENC(C7pqR2liF675VuEbQdv/S+O4wCHY5Lgx+XuF+gAeBCCVB18ykCPdjFIfjANw/KA4nBBsAxi/uF3vWH/PimefPQ==)
  secret: ENC(71ey5lTH3IAerQwhXbyfdP6R8vb2sz+A2ypn5SysxJa+SO3ZqXt7p+LrvOqMAXnH)

kakao:
  auth:
    url: https://kapi.kakao.com
  login:
    url: https://kauth.kakao.com
  redirect:
    login:
      uri: http://cground.store/lawgg-spring/api/public/kakao/login/redirect
    logout:
      uri: http://cground.store/lawgg-spring/api/public/kakao/logout/redirect
  client:
    id: ENC(nL/Dkn2NOC4bi/y2imKzGiCh7yYQD+xaktmWOcJJYUepL/xPd4JVPtluDnzLg9/zitTdNppHVFd7HFK5E3CsdpZtVOsbcUZ4/PtsFppi3h0=)
  secret: ENC(j+Jvpv9kqzIOt46Lo0VppBgUPbwkoFgO5s3fO68zA6tj3ONk8Y3uMWFPGbHJU34j0zrT8qa0UeU+bwr+jSy1RdAUOYimBRUj87urqdRCpqM=)
