aes:
  key: ENC(nMNNGmKR3mfj9WrAVSlsfJSbtWLGKMIINu0EZi2sGLzVpoKb3wC2QhrNApdiT+IyoTuZBe907JiqnPt0Q9GrxgzwPflO//16NNjBMERWtYg=)

lg:
  redirect:
    url:
      home: https://cground.store/lawgg
      login: https://cground.store/lawgg/login

token:
  key: ENC(xvK6dVxj9kBxialsqxZhY9hFunGuX4B/I59alGhszJsKCkXrmb2SC6N2pCC5Y7z9bn/LpLkdpLoZV6jadStAnW8gYtHjO0iFuV1BoeGM8lw=)

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
  mail:
    google:
      host: smtp.gmail.com
      username: ENC(Xr4rkO+eirBw3WtwLkCqCumPO4EXrq5uXSb5S8P36IDIkAgYCZD3nNSZ/gPmsgqb6I5pTirWxbwArUm2P3swjw==)
      password: ENC(oUJZvRndHDE4JslXIJkaMMml/85S/f5aNjvh1KmgdT8MtKHCpcxOS0NH1zfT1UsunTn1Ul6tn3jPXIJAYmuluQ==)
      port: 587
  redis:
    host: ENC(GgLwwMqj3uV2Ir6aH2qHqego0DssYsH8JnXdhYn3mHXJ7XEufTlpxnSdKQXrHfbb5ee/Ac/fchZ8evquy7gI6A==)
    port: 23699
    password: ENC(SJJK8XVpLRtcT3cBpzh1DG78NnhJmqjQ/ppznR6wf0UMiEZqAPtuoVzUJQyYSkch)
  config:
    activate:
      on-profile: prod

google: # 운영은 로우지지 계정으로 설정
  redirect: # 구글 로그인 콜백 URL (등록 필요)
    uri: http://cground.store/lawgg-spring/api/public/google/login/redirect
  client:
    id: ENC(QabZPzwFQTu5S7Agv+jJyldTB4u5HDrP+tV25ajHWkKt8uaEL7N4zj4YqPefb0r+oAnk9vCFyRjBf0JZ6LHnFUGrrfd1N3zoAfeFxDSu6pA=)
  secret: ENC(KEPMb6NhLiZr+JjJ2qqJkzv8DlRrdOVv7cpYf8lE/wegVlfgYFvwDBy+y8s2dQGq0G72ruPI0hYmK8DsRytGyy3U4siR16sQZVVbq/HYJgM=)

naver: # 운영은 로우지지 계정으로 설정
  redirect: # 네이버 로그인 콜백 URL (등록 필요)
    uri: http://cground.store/lawgg-spring/api/public/naver/login/redirect
  client:
    id: ENC(dDIGXFoIlq0tDwtnzy2NRxszNGZ+bX9Oat+L1qLsiJfQCs24rEkZltUQdcO9DQGvLpL6rJVy3Ux4/Bks89syxw==)
  secret: ENC(+6vs2ewUgYyvFcAlvG8y2eskG6Xq3VfyaV+SzBsvy+TkrwL/125v84LI8LpZQ7yY)

kakao: # 운영은 로우지지 계정으로 설정
  redirect:
    login: # 카카오 로그인 콜백 URL (등록 필요)
      uri: http://cground.store/lawgg-spring/api/public/kakao/login/redirect
    logout: # 카카오 로그아웃 콜백 URL (등록 필요)
      uri: http://cground.store/lawgg-spring/api/public/kakao/logout/redirect
  client:
    id: ENC(B25W24lylSyzENGt7DZuZ4bf02ZoJjPONHwGyjd4BA2rF1A4a3/ZFnJQ5fIFj746LmYwsrk3q0+sMdi+a+jRm48uGFIk6o74beu+ebK/leg=)
  secret: ENC(XGwdt4ki0xT+JEDN0W6goFMY/PqnNcU/hw6XzGIYYywLVL/FAHvkDpAeoo9zS6hPO9RSUrSp2jY0anUYbriKGBtCJgasu7HYgtlNrd+86Zc=)