server:
  port: 19001

spring:
  application:
    name: lawgg-web
  config:
#    import: optional:configserver:http://spring-cloud-config:8888/ # spring cloud config 정보 조회 (서버 종료 option 처리)
    import: optional:configserver:http://192.168.0.3:8888/ # spring cloud config 정보 조회 (서버 종료 option 처리)
  profiles:
    active: local
    group:
      local:
        - console-logging # 콘솔 로깅만 사용
      test:
        - console-logging
        - file-logging # 파일 로깅 사용
      prod:
        - console-logging
        - file-logging # 파일 로깅 사용
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl # java에서 선언했던 변수 이름을 테이블 매핑시
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl # java에서 선언했던 변수 이름을 테이블 매핑시에 그대로 사용한다는 뜻
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  servlet:
    multipart:
      max-file-size: 500MB # 요청 파일 하나의 사이즈
      max-request-size: 500MB # 요청 파일 총 사이즈
  data:
    redis:
      repositories:
        enabled: false # redis repositories 미사용 처리

mybatis:
  type-aliases-package: com.kr.lg.mapper
  mapper-locations: classpath:mapper/*.xml

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: alpha
  model-and-view-allowed: true

#eureka:
#  instance:
#    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
#    leaseRenewalIntervalInSeconds: 10
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka/