aes:
  key: ENC(nMNNGmKR3mfj9WrAVSlsfJSbtWLGKMIINu0EZi2sGLzVpoKb3wC2QhrNApdiT+IyoTuZBe907JiqnPt0Q9GrxgzwPflO//16NNjBMERWtYg=)

lg:
  redirect:
    url:
      home: http://localhost:8080/lawgg
      login: http://localhost:8080/lawgg/login

token:
  key: ENC(xvK6dVxj9kBxialsqxZhY9hFunGuX4B/I59alGhszJsKCkXrmb2SC6N2pCC5Y7z9bn/LpLkdpLoZV6jadStAnW8gYtHjO0iFuV1BoeGM8lw=)

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
  mail:
    google:
      host: smtp.gmail.com
      username: ENC(Lk0dKUD0pcJlm2qHavIn4VKi2OPONEBTokAaGZ/4+NJsvsze2+ZgkS80yD5v8/VbAm69nGlli/c5xSXAAXjVzQ==)
      password: ENC(EFNYRs7rjs5O8bPWEUQ5eVbWFPbZ3kYOV6GI1Jw7LUo6CRXuU2AY1U67Mw7dmxTFK+WiAW3/AWUVzprTNRoGSg==)
      port: 587
  redis:
    host: ENC(GgLwwMqj3uV2Ir6aH2qHqego0DssYsH8JnXdhYn3mHXJ7XEufTlpxnSdKQXrHfbb5ee/Ac/fchZ8evquy7gI6A==)
    port: 23699
    password: ENC(SJJK8XVpLRtcT3cBpzh1DG78NnhJmqjQ/ppznR6wf0UMiEZqAPtuoVzUJQyYSkch)
  config:
    activate:
      on-profile: local

google: # 로컬은 개인 계정으로 설정
  redirect: # 구글 로그인 콜백 URL (등록 필요)
    uri: http://localhost:19001/lawgg/google/login/callback
  client:
    id: ENC(IGl59N1wTjN+wWRcY3iJsC4Vj5cRsVmicaIugYCFJG2M1pa0q+0dDht/hQ7as1tUrmjVNifKuUxiGwdHPmijmj+fBE+FNAY/hPhj2tDWpJ8=)
  secret: ENC(u1WyUSfdY3sqB3TfWGj1R2E8Vis3OLELOMdV1fgjH6pDtbdqZ1SQhJEfG1WqE1rvOdzHTFOTez7HKcyDIbd/QEJsXq0/sAdm004x40jrCBw=)

naver: # 로컬은 개인 계정으로 설정
  redirect: # 네이버 로그인 콜백 URL (등록 필요)
    uri: http://localhost:19001/lawgg/naver/login/callback
  client:
    id: ENC(C7pqR2liF675VuEbQdv/S+O4wCHY5Lgx+XuF+gAeBCCVB18ykCPdjFIfjANw/KA4nBBsAxi/uF3vWH/PimefPQ==)
  secret: ENC(71ey5lTH3IAerQwhXbyfdP6R8vb2sz+A2ypn5SysxJa+SO3ZqXt7p+LrvOqMAXnH)

kakao: # 로컬은 개인 계정으로 설정
  redirect:
    login: # 카카오 로그인 콜백 URL (등록 필요)
      uri: http://localhost:19001/lawgg/kakao/login/callback
    logout: # 카카오 로그아웃 콜백 URL (등록 필요)
      uri: http://localhost:19001/lawgg/api/public/kakao/logout/redirect
  client:
    id: ENC(nL/Dkn2NOC4bi/y2imKzGiCh7yYQD+xaktmWOcJJYUepL/xPd4JVPtluDnzLg9/zitTdNppHVFd7HFK5E3CsdpZtVOsbcUZ4/PtsFppi3h0=)
  secret: ENC(j+Jvpv9kqzIOt46Lo0VppBgUPbwkoFgO5s3fO68zA6tj3ONk8Y3uMWFPGbHJU34j0zrT8qa0UeU+bwr+jSy1RdAUOYimBRUj87urqdRCpqM=)
