

---
spring:
  config:
    activate:
      on-profile: local
token:
  access-expired-time: 3600
  refresh-expired-time: 604800
lg:
  logout:
    url: http://localhost:8080/

---
spring:
  config:
    activate:
      on-profile: test
token:
  access-expired-time: 3600
  refresh-expired-time: 604800
lg:
  logout:
    url: https://cground.store/lawgg/

---
spring:
  config:
    activate:
      on-profile: prod
token:
  access-expired-time: 3600
  refresh-expired-time: 604800
lg:
  logout:
    url: https://cground.store/lawgg/