lg:
  redirect:
    url:
      home: https://cground.store/lawgg
      login: https://cground.store/lawgg/login

portone:
  rest:
    key: ENC(ZZ02Cc5d0J859mcQUIViypAVpREP72m+hAPDia/3Gynu9+y3zOAfjFat+fxRZZjrLIe32Da4ceViVWeJUbVLzA==)
    secret: ENC(GTUQ/3h3/tK4Qa/KskCOtZiJNdpX0/7Yon4gccyavWeCqe/uSfmSD8AfUpwtXLzqvny4i/HcPi0nXEJlYQecwn5OKo7x9ttKBIiHQ96GIBChCsmEMzb6jTP5z5dAZ/87umy/Z7JYaXb/kECzeq4xazPbT3k9Mdj+Tb6RHGptN24=)
  url:
    token: https://api.iamport.kr/
    certificate: https://api.iamport.kr/certifications/